[2018-05-03 00:18:44 +0200] [17857] [DEBUG] Current configuration:
  daemon: False
  reload_engine: auto
  backlog: 2048
  paste: None
  reload: False
  syslog: False
  on_starting: <function OnStarting.on_starting at 0x7f01a70cbea0>
  pythonpath: None
  limit_request_field_size: 8190
  cert_reqs: 0
  worker_int: <function WorkerInt.worker_int at 0x7f01a70da8c8>
  child_exit: <function ChildExit.child_exit at 0x7f01a70df0d0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f01a70df400>
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-SSL': 'on', 'X-FORWARDED-PROTO': 'https'}
  worker_abort: <function WorkerAbort.worker_abort at 0x7f01a70daa60>
  workers: 1
  max_requests: 0
  raw_env: []
  worker_exit: <function WorkerExit.worker_exit at 0x7f01a70df268>
  graceful_timeout: 30
  pidfile: /var/run/gunicorn.pid
  user: 0
  group: 0
  forwarded_allow_ips: ['127.0.0.1']
  proxy_protocol: False
  raw_paste_global_conf: []
  spew: False
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f01a70da730>
  on_exit: <function OnExit.on_exit at 0x7f01a70df598>
  check_config: False
  proxy_allow_ips: ['127.0.0.1']
  keepalive: 2
  syslog_facility: user
  proc_name: None
  worker_class: eventlet
  max_requests_jitter: 0
  post_request: <function PostRequest.post_request at 0x7f01a70daea0>
  umask: 0
  tmp_upload_dir: None
  errorlog: /home/nicola/Documenti/Lavoro/UnionService/Server/log/gunicorn.log
  pre_exec: <function PreExec.pre_exec at 0x7f01a70dabf8>
  ca_certs: None
  timeout: 30
  pre_fork: <function Prefork.pre_fork at 0x7f01a70da400>
  limit_request_fields: 100
  sendfile: None
  post_fork: <function Postfork.post_fork at 0x7f01a70da598>
  certfile: None
  pre_request: <function PreRequest.pre_request at 0x7f01a70dad90>
  worker_tmp_dir: None
  accesslog: None
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  syslog_prefix: None
  statsd_host: None
  statsd_prefix: 
  chdir: /home/nicola/Documenti/Lavoro/UnionService/Server
  ssl_version: 2
  threads: 1
  suppress_ragged_eofs: True
  default_proc_name: Server:application
  loglevel: debug
  on_reload: <function OnReload.on_reload at 0x7f01a70da0d0>
  preload_app: False
  initgroups: False
  do_handshake_on_connect: False
  syslog_addr: udp://localhost:514
  enable_stdio_inheritance: False
  when_ready: <function WhenReady.when_ready at 0x7f01a70da268>
  worker_connections: 1000
  config: None
  keyfile: None
  ciphers: TLSv1
  limit_request_line: 4094
  bind: ['127.0.0.1:3000']
[2018-05-03 00:18:44 +0200] [17857] [INFO] Starting gunicorn 19.7.1
[2018-05-03 00:18:44 +0200] [17857] [DEBUG] Arbiter booted
[2018-05-03 00:18:44 +0200] [17857] [INFO] Listening at: http://127.0.0.1:3000 (17857)
[2018-05-03 00:18:44 +0200] [17857] [INFO] Using worker: eventlet
[2018-05-03 00:18:44 +0200] [17861] [INFO] Booting worker with pid: 17861
[2018-05-03 00:18:44 +0200] [17857] [DEBUG] 1 workers
[2018-05-03 00:18:45 +0200] [17861] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/gunicorn/workers/geventlet.py", line 103, in init_process
    super(EventletWorker, self).init_process()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.local/share/virtualenvs/Server-WjXv57Cf/lib/python3.5/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/nicola/Documenti/Lavoro/UnionService/Server/Server.py", line 1, in <module>
    from app import server as application, manager
  File "/home/nicola/Documenti/Lavoro/UnionService/Server/app/__init__.py", line 7, in <module>
    from app.model.dbManager import DBManager
  File "/home/nicola/Documenti/Lavoro/UnionService/Server/app/model/dbManager.py", line 5, in <module>
    from app.model.db.dbManagerModules.managerDipendente import ManagerDipendente
  File "/home/nicola/Documenti/Lavoro/UnionService/Server/app/model/db/dbManagerModules/managerDipendente.py", line 1, in <module>
    from app.model.dipendente import Dipendente
  File "/home/nicola/Documenti/Lavoro/UnionService/Server/app/model/dipendente.py", line 1, in <module>
    from app.model.db.dipendenteDBmodel import DipendenteDBmodel
  File "/home/nicola/Documenti/Lavoro/UnionService/Server/app/model/db/dipendenteDBmodel.py", line 2, in <module>
    from app import databaseManager
ImportError: cannot import name 'databaseManager'
[2018-05-03 00:18:45 +0200] [17861] [INFO] Worker exiting (pid: 17861)
[2018-05-03 00:18:45 +0200] [17857] [INFO] Shutting down: Master
[2018-05-03 00:18:45 +0200] [17857] [INFO] Reason: Worker failed to boot.
